### ISSUE TITLE
加壳app是否可以检测？

### ISSUE THREAD

**Issue by TBOsec** [ChenJunsen/Hegui3.0#2]
virtualXposed和该模块可以对app的行为检测，但当运行加壳app时无法使用，加壳app会一直处于加载中，
请问有什么办法可以解决吗？

**Comment by ChenJunsen** [comment]
不清楚你的加壳app是哪种，如果你加壳混淆了系统方法，那就没法检测了。

**Comment by TBOsec** [comment]
> 不清楚您的加壳应用程序是哪种，加壳应用程序混淆了系统方法，那么就没有检测了。

使用的是爱加密企业版加固，加固后的app不能检测 ”提前收集行为“；
现在app应该都有加固，那您那边做app检测时，是在加固前测试合规，还是加固后测试合规呢？
