### ISSUE TITLE
有什么方案可以检测App自启动，特别是第三方SDK的检测？

### ISSUE THREAD

**Issue by AnyQuestion007** [ChenJunsen/Hegui3.0#9]
现在还会检查应用自启动的情况，除了App自身的配置，还会检查第三方SDK，不知道有没有办法检测出来

**Comment by ChenJunsen** [comment]
你说的自启动应该类似app保活。安卓官方没有自启动的API。提供一些思路：目前的app自启动大多靠广播拉起。监听系统启动后然后发送一个启动app的广播，或者通过一个应用拉起另一个应用。

**Comment by AnyQuestion007** [comment]
谢谢，照这个思路试一试
